server:
  port: 8080

spring:
  datasource:
    username: tenvisapi_2020
    password: tws20200120$#@Qaz
    url: jdbc:mysql://newtenvispublic.mysql.rds.aliyuncs.com:3981/tenvis_api?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ldy.domain